# ---  
# - hosts: all 

#   tasks:   
#   - name: cpu_info
#     script: test.py 
---
- name: Hello World!
  hosts: 10.147.20.79
  remote_user: zc
 
  tasks:
 
  - name: Issue code
    copy: "src=sysinfotest.py dest=/home/zc/work"